### PR TITLE
http2: close connections when receiving too many headers

### LINKED ISSUE #30: HTTP/2 continuation flood (FYI) ?
https://deps.dev/advisory/osv/GO-2024-2687

image

### PR DESCRIPTION
**Pull request by Weaxs**
FIX https://github.com/hertz-contrib/http2/issues/30#event-12533550901

Refer to [https://go-review.googlesource.com/c/net/+/576155](https://go-review.googlesource.com/c/net/+/576155)

## extras
This pr https://github.com/hertz-contrib/http2/pull/31 is already update `golang.org/x/net` version, 
but the  cause of Http2 CONTINUATION flood maybe is `frame.go`
This project is forked from [net/http2](https://github.com/golang/net/tree/master/http2), should update `frame.go` I guess?

### CODE REVIEW

**Comment by Weaxs** [comment]
@li-jin-gou can you help to review this pr ?

**Comment by li-jin-gou** [comment]
> @li-jin-gou can you help to review this pr ?

I'll get professional help CR.

**Comment by li-jin-gou** [comment]
ci need to fix

**Comment by Duslia** [comment]
And also ci

**Review by Duslia — APPROVED** [review]

**Comment by Duslia** [comment]
LGTM, thanks a lot

**Pull request merged**
